2019-03-14 17:49:36,911 - invest- ERROR - 这是一个错误 - [logger.py:20]
2019-03-14 17:49:50,861 - invest- ERROR - 这是一个错误 - [logger.py:20]
2019-03-14 17:52:53,040 - invest- ERROR - 这是一个错误 - [logger.py:21]
2019-03-14 17:52:53,055 - login_test- INFO - 开始执行第1个测试用例： - [test_login.py:20]
2019-03-14 17:52:53,189 - login_test- INFO - 开始执行第2个测试用例： - [test_login.py:20]
2019-03-14 17:53:57,325 - invest- ERROR - 这是一个错误 - [logger.py:21]
2019-03-14 17:53:57,340 - login_test- INFO - 开始执行第1个测试用例： - [test_login.py:20]
2019-03-14 17:53:57,492 - login_test- INFO - 开始执行第2个测试用例： - [test_login.py:20]
2019-03-15 10:15:05,013 - login_test- INFO - 开始执行第1个测试用例： - [test_login.py:20]
2019-03-15 10:15:05,157 - login_test- INFO - 开始执行第2个测试用例： - [test_login.py:20]
2019-03-15 10:16:23,700 - login_test- INFO - 开始执行第1个测试用例： - [test_login.py:20]
2019-03-15 10:16:23,847 - login_test- INFO - 开始执行第2个测试用例： - [test_login.py:20]
